sonar.projectKey=crafts-ecommerce
sonar.projectName=Crafts E-Commerce
sonar.projectVersion=0.1.0

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/.next/**,**/public/**,**/*.test.ts,**/*.spec.ts,**/*.test.tsx,**/*.spec.tsx

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.tsconfigPaths=tsconfig.json

sonar.sourceEncoding=UTF-8
